import localFont from "next/font/local";
import "./globals.css";
import { Epilogue } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

const epilogue = Epilogue({
	subsets: ["latin"],
	display: "swap",
});

// const poppins = Poppins({
// 	subsets: ["latin"],
// 	display: "swap",
// });

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased ${epilogue.className} bg-gray-100`}
			>
				<Header />
				{children}
				{/* <Footer /> */}
			</body>
		</html>
	);
}
